import { Download, Clock, FileText, Circle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  type TrustNarrative,
  type ScoreState,
  getScoreStateConfig,
} from "@/lib/trustNarrative";

interface TrustNarrativeCardProps {
  narrative: TrustNarrative;
  compact?: boolean;
}

function formatAssessedDate(iso: string): string {
  const d = new Date(iso);
  return `Assessed on ${d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })} at ${d.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
    timeZoneName: "short",
  })}`;
}

function exportNarrativePdf(narrative: TrustNarrative) {
  const config = getScoreStateConfig(narrative.score_state as ScoreState);
  const assessedDate = formatAssessedDate(narrative.assessed_at);

  const content = `
VAULTA ASSESSMENT RECORD
For institutional use only. This document reflects the output of an automated assessment and does not constitute a lending recommendation.

─────────────────────────────────────────

Institution: ${narrative.institution_name ?? "N/A"}
Assessment ID: ${narrative.assessment_id}
Score State: ${config.label}
Trust Score: ${narrative.trust_score ?? "N/A"}
Documents Assessed: ${narrative.document_count}
${assessedDate}

─────────────────────────────────────────

NARRATIVE

${narrative.narrative_text}

─────────────────────────────────────────

Generated by Vaulta Trust Platform
This record is immutable and cannot be altered after generation.
  `.trim();

  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `vaulta-assessment-${narrative.assessment_id.slice(0, 8)}-${
    new Date(narrative.assessed_at).toISOString().split("T")[0]
  }.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function TrustNarrativeCard({ narrative, compact }: TrustNarrativeCardProps) {
  const config = getScoreStateConfig(narrative.score_state as ScoreState);

  return (
    <Card
      className={`border-l-4 ${config.borderColor} border-border bg-card`}
    >
      <CardContent className={compact ? "py-3 px-4" : "pt-5"}>
        {/* Header row */}
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <Circle
              className={`${config.textColor} fill-current`}
              size={10}
            />
            <Badge variant={config.badgeVariant} className="text-xs font-medium">
              {config.label}
            </Badge>
            {narrative.trust_score !== null && (
              <span className="text-xs text-muted-foreground font-mono">
                Score: {narrative.trust_score}/100
              </span>
            )}
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs text-muted-foreground flex items-center gap-1">
              <FileText size={12} />
              {narrative.document_count} doc{narrative.document_count !== 1 ? "s" : ""}
            </span>
            <Button
              variant="ghost"
              size="sm"
              className="h-7 px-2 text-xs gap-1"
              onClick={() => exportNarrativePdf(narrative)}
            >
              <Download size={12} />
              Export
            </Button>
          </div>
        </div>

        {/* Narrative text */}
        <p className="text-sm text-foreground leading-relaxed mb-3">
          {narrative.narrative_text}
        </p>

        {/* Timestamp — locked, immutable */}
        <div className="flex items-center gap-1 text-xs text-muted-foreground">
          <Clock size={11} />
          {formatAssessedDate(narrative.assessed_at)}
        </div>
      </CardContent>
    </Card>
  );
}

export function ScoreStateIndicator({ state }: { state: ScoreState }) {
  const config = getScoreStateConfig(state);
  return (
    <div className="flex items-center gap-1.5">
      <Circle className={`${config.textColor} fill-current`} size={8} />
      <span className={`text-xs font-medium ${config.textColor}`}>
        {config.label}
      </span>
    </div>
  );
}
