import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function escPdf(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function generateAssessmentPdf(data: {
  id: string;
  applicant_name: string;
  reference_id: string;
  submitted_at: string;
  assessed_at: string;
  document_count: number;
  trust_score: number;
  score_state: string;
  assessment_narrative: string;
  document_types: string[];
}): Uint8Array {
  let stream = '';

  const text = (str: string, x: number, y: number, font: string, size: number) => {
    stream += `BT /${font} ${size} Tf ${x} ${y} Td (${escPdf(str)}) Tj ET\n`;
  };

  const line = (x1: number, y1: number, x2: number, y2: number, w: number, g: number) => {
    stream += `${g} G ${w} w ${x1} ${y1} m ${x2} ${y2} l S\n`;
  };

  let y = 742;

  // Header
  text('VAULTA', 50, y, 'F2', 22);
  y -= 16;
  text('ASSESSMENT RECORD', 50, y, 'F1', 10);
  y -= 12;
  text(`Certificate ID: ${data.id.substring(0, 8).toUpperCase()}`, 50, y, 'F1', 8);
  y -= 20;
  line(50, y, 562, y, 1, 0.15);
  y -= 30;

  // Fields
  const field = (label: string, value: string) => {
    text(label, 50, y, 'F2', 10);
    text(value, 200, y, 'F1', 10);
    y -= 20;
  };

  field('Applicant:', data.applicant_name);
  field('Reference ID:', data.reference_id);
  field('Submitted:', data.submitted_at);
  field('Assessed:', data.assessed_at);
  field('Documents:', String(data.document_count));
  field('Trust Score:', `${data.trust_score} / 100`);

  const stateLabels: Record<string, string> = {
    clear: 'CLEAR', review: 'UNDER REVIEW', flag: 'FLAGGED', insufficient: 'INSUFFICIENT',
  };
  field('Result:', stateLabels[data.score_state] || data.score_state.toUpperCase());
  y -= 10;

  // Narrative
  line(50, y, 562, y, 0.5, 0.8);
  y -= 25;
  text('Assessment Narrative', 50, y, 'F2', 13);
  y -= 22;

  const words = (data.assessment_narrative || 'No narrative available.').split(' ');
  let currentLine = '';
  for (const word of words) {
    const test = currentLine ? `${currentLine} ${word}` : word;
    if (test.length > 80) {
      text(currentLine, 50, y, 'F1', 10);
      y -= 15;
      currentLine = word;
    } else {
      currentLine = test;
    }
  }
  if (currentLine) { text(currentLine, 50, y, 'F1', 10); y -= 28; }

  // Document types
  text('Document Types Received', 50, y, 'F2', 13);
  y -= 20;
  for (const t of (data.document_types || [])) {
    text(`\u2022  ${t}`, 60, y, 'F1', 10);
    y -= 16;
  }
  y -= 25;

  // Footer
  line(50, y, 562, y, 0.5, 0.85);
  y -= 18;
  text('This document is a structured assessment output generated by Vaulta.', 50, y, 'F1', 7);
  y -= 11;
  text('It contains no raw document images or applicant-submitted files.', 50, y, 'F1', 7);
  y -= 11;
  text(`Generated: ${new Date().toISOString()} UTC  |  Vaulta Institutional Platform`, 50, y, 'F1', 7);

  // Build PDF structure
  const objs = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>\nendobj\n',
    `4 0 obj\n<< /Length ${stream.length} >>\nstream\n${stream}endstream\nendobj\n`,
    '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj\n',
    '6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>\nendobj\n',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  for (const obj of objs) { offsets.push(pdf.length); pdf += obj; }

  const xrefPos = pdf.length;
  pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  for (const o of offsets) { pdf += `${o.toString().padStart(10, '0')} 00000 n \n`; }
  pdf += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xrefPos}\n%%EOF`;

  return new TextEncoder().encode(pdf);
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_ANON_KEY')!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: userErr } = await supabase.auth.getUser();
    if (userErr || !user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const { submission_id } = await req.json();
    if (!submission_id) {
      return new Response(JSON.stringify({ error: 'submission_id required' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const admin = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    );

    const { data: sub, error: subErr } = await admin
      .from('intake_submissions')
      .select('*')
      .eq('id', submission_id)
      .single();

    if (subErr || !sub) {
      return new Response(JSON.stringify({ error: 'Submission not found' }), {
        status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Verify membership
    const { data: membership } = await admin
      .from('institutional_users')
      .select('id')
      .eq('user_id', user.id)
      .eq('institution_id', sub.institution_id)
      .single();

    if (!membership) {
      return new Response(JSON.stringify({ error: 'Access denied' }), {
        status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const pdfBytes = generateAssessmentPdf({
      ...sub,
      submitted_at: new Date(sub.submitted_at).toUTCString(),
      assessed_at: sub.assessed_at ? new Date(sub.assessed_at).toUTCString() : 'Pending',
    });

    return new Response(pdfBytes, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="vaulta-assessment-${sub.reference_id}.pdf"`,
      },
    });
  } catch (err) {
    console.error('PDF export error:', err);
    return new Response(JSON.stringify({ error: 'Internal server error' }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
